dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.6'
    env: TOXENV=docs
  - python: '3.6'
    env: TOXENV=manifest
install:
- pip install tox
script:
- tox
notifications:
  email: false
deploy:
  provider: pypi
  user: spotify_alf
  password:
    secure: ncAmzPE9EcT96CJUE001+LP4xcekLV4zUhXBfEEP11JdcSJbCml8ev+IQabs8Gbm5YHW2oj9jULPCXgV4lW9OXS71oSnaZB+D3MWyrO+Fl61/nmHZRcpVtxIbYOcPcRr713vj6hX1GLG8Tci4//ZgDaCHUDIq0OjzLajQ/fiGjwrANj5PLVBplhMcjiTCAxL1sWMT9RM3bBnj8VHrfy9UIqCipyXg+nRZSGoFOZTCWmp+wKvzDQldCcwMeBMuYgQllt4mjdBMBsgQC4hy/dssizy1XN3+dGyiNEo7SnifUM/KpJnC9bEFL4MoDfK9Wt6mUfdxVFls/xZmO+Apzc+QRPcd75X+clXETwhwmJjb0+Dkn9zSS2haoek7DrIkJihQIZz3TjXm7GERbvgPOURcKHSZd0sPPy7XRib0CWZx6QGFmTuNkFWMfgcVHEqlmyHvAlFhUuhJD/5XX6d7SnB9Le/6uE6yy21wfH9Ox9h38QqBHP5O80xaRkAnJUS4dokhun0UD6WD4+mGhKg+2mfyOBii5lvAmBMNTWRho/BbtI580k/9ADIV0N040ZOVVAE2/n6UOQln5X2FggVBNha1MY7lFZ0val+crVDRGUGCIgSwu8oWSvJQkdkktd+Y+qnQ2m6rAeDtkJwMYM4s4nozOJIGfvGGtoJQuFKalCh+TY=
  on:
    tags: true
    branch: master
    condition: $TOXENV = py36
  distributions: sdist bdist_wheel
